export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_STREAM = 'CREATE_STREAM';
export const FETCH_STREAMS = 'FETCH_STREAMS';
export const FETCH_STREAM = 'FETCH_STREAM';
export const DELETE_STREAM = 'DELETE_STREAM';
export const EDIT_STREAM = 'EDIT_STREAM';
export const FETCH_MYROOM = 'FETCH_MYROOM';
export const CREATE_USER = 'CREATE_USER';
export const INITIATE_SHAPEGAME = 'INITIATE_SHAPEGAME';
export const ADD_ME_TO_MYROOM = 'ADD_ME_TO_MYROOM';
export const UPDATE_USERS_IN_MYROOM = 'UPDATE_USERS_IN_MYROOM';

